export const ROUTES = {
  HOME: '/',
  SOLUTIONS: '/solutions',
  CASE_STUDIES: '/case-studies',
  SERVICES: '/services',
  WEB_DEVELOPMENT: '/services/web-development',
  APP_DEVELOPMENT: '/services/app-development',
  CLOUD_SERVICES: '/services/cloud-services',
  INSIGHTS: '/insights',
  ABOUT: '/about',
  CAREERS: '/careers',
  CONTACT: '/contact',
  LOGIN: '/login',
  PRIVACY: '/privacy',
  TERMS: '/terms',
  REFUND: '/refund',
  GDPR: '/gdpr',
  NOT_FOUND: '*',
};
